"""initial

Revision ID: f0a45253e5c8
Revises: 
Create Date: 2026-05-14 11:38:22.272609

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_log_created_at'), 'app_log', ['created_at'], unique=False)
    op.create_table('backtest_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.String(length=100), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('sharpe', sa.Float(), nullable=True),
    sa.Column('drawdown', sa.Float(), nullable=True),
    sa.Column('sessions_used', sa.Integer(), nullable=True),
    sa.Column('ran_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('combo_search_study',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_dwcs', sa.Boolean(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_name'), 'event', ['name'], unique=True)
    op.create_table('fighter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('ufcstats_url', sa.Text(), nullable=False),
    sa.Column('tapology_url', sa.Text(), nullable=True),
    sa.Column('record', sa.String(length=20), nullable=True),
    sa.Column('stance', sa.String(length=20), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('reach_cm', sa.Float(), nullable=True),
    sa.Column('dob', sa.DateTime(timezone=True), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('ufcstats_url')
    )
    op.create_index(op.f('ix_fighter_name'), 'fighter', ['name'], unique=False)
    op.create_table('hp_search_study',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_short', sa.String(length=50), nullable=False),
    sa.Column('feature_set', sa.String(length=10), nullable=False),
    sa.Column('feat_type', sa.String(length=10), nullable=False),
    sa.Column('dataset', sa.String(length=20), nullable=False),
    sa.Column('n_trials', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_bet_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lab_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short', sa.String(length=50), nullable=False),
    sa.Column('family', sa.String(length=20), nullable=False),
    sa.Column('default_feat_type', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_short'), 'model', ['short'], unique=True)
    op.create_table('scraping_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('new_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('recent_event_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cognito_sub', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_cognito_sub'), 'user', ['cognito_sub'], unique=True)
    op.create_table('bet_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_bet_config_user_name')
    )
    op.create_index(op.f('ix_bet_config_user_id'), 'bet_config', ['user_id'], unique=False)
    op.create_table('combo_search_trial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('trial_idx', sa.Integer(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['combo_search_study.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_combo_search_trial_study_id'), 'combo_search_trial', ['study_id'], unique=False)
    op.create_table('fight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('fighter_1_id', sa.Integer(), nullable=False),
    sa.Column('fighter_2_id', sa.Integer(), nullable=False),
    sa.Column('weight_class', sa.String(length=50), nullable=True),
    sa.Column('card_position', sa.String(length=20), nullable=True),
    sa.Column('scheduled_rounds', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('time', sa.String(length=10), nullable=True),
    sa.Column('odds_f1_american', sa.Integer(), nullable=True),
    sa.Column('odds_f2_american', sa.Integer(), nullable=True),
    sa.Column('real_winner', sa.String(length=255), nullable=True),
    sa.Column('fight_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fighter_1_id'], ['fighter.id'], ),
    sa.ForeignKeyConstraint(['fighter_2_id'], ['fighter.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'fighter_1_id', 'fighter_2_id', name='uq_fight_event_pair')
    )
    op.create_index(op.f('ix_fight_event_id'), 'fight', ['event_id'], unique=False)
    op.create_index('ix_fight_event_order', 'fight', ['event_id', 'fight_order'], unique=False)
    op.create_table('fighter_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fighter_id', sa.Integer(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['fighter_id'], ['fighter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fighter_raw_fighter_id'), 'fighter_raw', ['fighter_id'], unique=False)
    op.create_table('hp_search_trial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('trial_idx', sa.Integer(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['hp_search_study.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hp_search_trial_study_id'), 'hp_search_trial', ['study_id'], unique=False)
    op.create_table('model_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('version_idx', sa.Integer(), nullable=False),
    sa.Column('feature_set', sa.String(length=10), nullable=False),
    sa.Column('hp_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('artifact_uri', sa.Text(), nullable=False),
    sa.Column('sagemaker_model_name', sa.String(length=63), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('was_production', sa.Boolean(), nullable=False),
    sa.Column('starred', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'version_idx', name='uq_model_version_idx')
    )
    op.create_index(op.f('ix_model_version_model_id'), 'model_version', ['model_id'], unique=False)
    op.create_table('parlay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parlay_type', sa.String(length=10), nullable=False),
    sa.Column('legs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stake', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payout', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parlay_user_id'), 'parlay', ['user_id'], unique=False)
    op.create_table('prediction_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_session_event_id'), 'prediction_session', ['event_id'], unique=False)
    op.create_table('tapology_event_match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ufcstats_event_id', sa.Integer(), nullable=False),
    sa.Column('tapology_slug', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ufcstats_event_id'], ['event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ufcstats_event_id', 'tapology_slug', name='uq_tap_event_match')
    )
    op.create_index(op.f('ix_tapology_event_match_ufcstats_event_id'), 'tapology_event_match', ['ufcstats_event_id'], unique=False)
    op.create_table('user_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_user_pref')
    )
    op.create_index(op.f('ix_user_preference_user_id'), 'user_preference', ['user_id'], unique=False)
    op.create_table('user_view_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('view', sa.String(length=100), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'view', name='uq_user_view')
    )
    op.create_index(op.f('ix_user_view_state_user_id'), 'user_view_state', ['user_id'], unique=False)
    op.create_table('active_model',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sagemaker_target_model', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['model_version.id'], ),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_table('fight_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fight_id', sa.Integer(), nullable=False),
    sa.Column('feature_set', sa.String(length=10), nullable=False),
    sa.Column('vector', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('before_event_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fight_id'], ['fight.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fight_id', 'feature_set', name='uq_fight_features_set')
    )
    op.create_index(op.f('ix_fight_features_fight_id'), 'fight_features', ['fight_id'], unique=False)
    op.create_table('prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('fight_id', sa.Integer(), nullable=False),
    sa.Column('model_short', sa.String(length=50), nullable=False),
    sa.Column('version_idx', sa.Integer(), nullable=False),
    sa.Column('prob_f1', sa.Float(), nullable=False),
    sa.Column('prob_f2', sa.Float(), nullable=False),
    sa.Column('method_pred', sa.String(length=50), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['fight_id'], ['fight.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['prediction_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'fight_id', 'model_short', name='uq_prediction_session_fight_model')
    )
    op.create_index(op.f('ix_prediction_fight_id'), 'prediction', ['fight_id'], unique=False)
    op.create_index(op.f('ix_prediction_session_id'), 'prediction', ['session_id'], unique=False)
    op.create_table('prediction_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'model_version_id', name='uq_prediction_cache_ev_mv')
    )
    op.create_index(op.f('ix_prediction_cache_event_id'), 'prediction_cache', ['event_id'], unique=False)
    op.create_table('publish_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('log_excerpt', sa.Text(), nullable=True),
    sa.Column('ran_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publish_run_model_version_id'), 'publish_run', ['model_version_id'], unique=False)
    op.create_table('tapology_picks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fight_id', sa.Integer(), nullable=False),
    sa.Column('total_picks', sa.Integer(), nullable=False),
    sa.Column('fighter_a_id', sa.Integer(), nullable=False),
    sa.Column('fighter_b_id', sa.Integer(), nullable=False),
    sa.Column('fighter_a_win_pct', sa.Float(), nullable=True),
    sa.Column('fighter_b_win_pct', sa.Float(), nullable=True),
    sa.Column('fighter_a_methods', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fighter_b_methods', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('matchup_url', sa.Text(), nullable=True),
    sa.Column('source_event_url', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fight_id'], ['fight.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fighter_a_id'], ['fighter.id'], ),
    sa.ForeignKeyConstraint(['fighter_b_id'], ['fighter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tapology_picks_fight_id'), 'tapology_picks', ['fight_id'], unique=True)
    op.create_table('training_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('request', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('result_version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.ForeignKeyConstraint(['result_version_id'], ['model_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_bet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fight_id', sa.Integer(), nullable=False),
    sa.Column('stake', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('predicted_pick', sa.String(length=255), nullable=False),
    sa.Column('odds_taken_american', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fight_id'], ['fight.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_bet_user_id'), 'user_bet', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_bet_user_id'), table_name='user_bet')
    op.drop_table('user_bet')
    op.drop_table('training_session')
    op.drop_index(op.f('ix_tapology_picks_fight_id'), table_name='tapology_picks')
    op.drop_table('tapology_picks')
    op.drop_index(op.f('ix_publish_run_model_version_id'), table_name='publish_run')
    op.drop_table('publish_run')
    op.drop_index(op.f('ix_prediction_cache_event_id'), table_name='prediction_cache')
    op.drop_table('prediction_cache')
    op.drop_index(op.f('ix_prediction_session_id'), table_name='prediction')
    op.drop_index(op.f('ix_prediction_fight_id'), table_name='prediction')
    op.drop_table('prediction')
    op.drop_index(op.f('ix_fight_features_fight_id'), table_name='fight_features')
    op.drop_table('fight_features')
    op.drop_table('active_model')
    op.drop_index(op.f('ix_user_view_state_user_id'), table_name='user_view_state')
    op.drop_table('user_view_state')
    op.drop_index(op.f('ix_user_preference_user_id'), table_name='user_preference')
    op.drop_table('user_preference')
    op.drop_index(op.f('ix_tapology_event_match_ufcstats_event_id'), table_name='tapology_event_match')
    op.drop_table('tapology_event_match')
    op.drop_index(op.f('ix_prediction_session_event_id'), table_name='prediction_session')
    op.drop_table('prediction_session')
    op.drop_index(op.f('ix_parlay_user_id'), table_name='parlay')
    op.drop_table('parlay')
    op.drop_index(op.f('ix_model_version_model_id'), table_name='model_version')
    op.drop_table('model_version')
    op.drop_index(op.f('ix_hp_search_trial_study_id'), table_name='hp_search_trial')
    op.drop_table('hp_search_trial')
    op.drop_index(op.f('ix_fighter_raw_fighter_id'), table_name='fighter_raw')
    op.drop_table('fighter_raw')
    op.drop_index('ix_fight_event_order', table_name='fight')
    op.drop_index(op.f('ix_fight_event_id'), table_name='fight')
    op.drop_table('fight')
    op.drop_index(op.f('ix_combo_search_trial_study_id'), table_name='combo_search_trial')
    op.drop_table('combo_search_trial')
    op.drop_index(op.f('ix_bet_config_user_id'), table_name='bet_config')
    op.drop_table('bet_config')
    op.drop_index(op.f('ix_user_cognito_sub'), table_name='user')
    op.drop_table('user')
    op.drop_table('scraping_run')
    op.drop_index(op.f('ix_model_short'), table_name='model')
    op.drop_table('model')
    op.drop_table('lab_preference')
    op.drop_table('lab_bet_config')
    op.drop_table('hp_search_study')
    op.drop_index(op.f('ix_fighter_name'), table_name='fighter')
    op.drop_table('fighter')
    op.drop_index(op.f('ix_event_name'), table_name='event')
    op.drop_table('event')
    op.drop_table('combo_search_study')
    op.drop_table('backtest_run')
    op.drop_index(op.f('ix_app_log_created_at'), table_name='app_log')
    op.drop_table('app_log')
    # ### end Alembic commands ###
